# ---
# Report Endpoint Documentation
#
# The /api/report/tumor-board endpoint returns a human-readable HTML report summarizing all synthetic variant records.
#
# - Reads data from data/synthetic_variants.csv (generated by scripts/synthetic_data.py)
# - Displays all variants in a formatted HTML table for easy review
# - Requires X-API-Key: changeme header for access
#
# How to use:
#   - Use Swagger UI, curl, or a browser with a custom header extension (e.g., ModHeader)
#   - Go to http://localhost:8000/api/report/tumor-board
#   - You will see a table of all synthetic variants
#
# This endpoint is intended for clinical/tumor board review and demonstration purposes.
# ---

import csv
from fastapi import APIRouter, Depends, Response
from backend.security import api_key_auth
import os

router = APIRouter()

@router.get("/tumor-board", dependencies=[Depends(api_key_auth)])
def tumor_board_report():
    # Read real synthetic variant data from CSV
    csv_path = os.path.join(os.path.dirname(__file__), '../../data/synthetic_variants.csv')
    variants = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            variants.append(row)
    # Generate HTML table
    html = """
    <html>
    <head><title>Tumor Board Variant Report</title></head>
    <body>
    <h2>Tumor Board Variant Report</h2>
    <table border='1' cellpadding='5' cellspacing='0'>
        <tr>
            <th>Gene</th><th>Transcript</th><th>Protein Change</th><th>Genome Build</th><th>Tumor Type</th><th>TMB</th><th>Prior Therapy Count</th>
        </tr>
    """
    for v in variants:
        html += f"<tr><td>{v['gene']}</td><td>{v['transcript']}</td><td>{v['protein_change']}</td><td>{v['genome_build']}</td><td>{v['tumor_type']}</td><td>{v['tmb']}</td><td>{v['prior_therapy_count']}</td></tr>"
    html += """
    </table>
    </body>
    </html>
    """
    return Response(content=html, media_type="text/html")
